//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string id { get; set; }
        public Nullable<System.DateTime> create_day { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> otherCosts { get; set; }
        public string id_staff { get; set; }
        public string id_customer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
