//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string id_supplier { get; set; }
        public string name_supplier { get; set; }
        public string address_supplier { get; set; }
        public string id_product { get; set; }
        public string id_producttype { get; set; }
    }
}
